### ISSUE TITLE
Optimize compare time using batch interface

### ISSUE THREAD

**Issue by qizhou** [ethstorage/ethstorage-sdk#21]
One UX problem of `ethfs-cli` is the long comparison time if there are multiple local files.  To reduce the comparison time, one optimization is done at https://github.com/ethstorage/ethstorage-sdk/pull/17 to issue multiple RPC requests instead of one.  However, this approach faces the rate-limiting of RPC servers.

One optimization that can be done is to use a batch interface to get the data hashes of the files in a single RPC call.  Suppose we can get 10 data hashes per call, then we can reduce the time to 1/10x without worry about the rate-limiting issue.

**Comment by iteyelmp** [comment]
fix
